### ISSUE TITLE
What sort of output it is giving?

### ISSUE THREAD

**Issue by gourav1905** [sofiat-olaosebikan/hopcroftkarp#2]
Why all the elements are present twice in the dictionary returned.

**Comment by sofiatolaosebikan** [comment]
If in the maximum matching, there is an edge between vertex 1 and a, then you have {a:1, 1:a}. I hope this answered your question? Do you think this can be done in a better way?

**Comment by adammichaelwood** [comment]
I'm not sure what the practical use the duplicate pairs are. Any practical use case is going to have to take an extra step to filter them out

**Comment by adammichaelwood** [comment]
I've been playing around with this a little. I keep getting tripped up in internal logic, but I'd like to propose the following change:

Add an optional arg of `keys_only=False` to `.maximum_matching()`.
When False, behavior is as now.
When True, the final list is filtered so only key,value pairs are returned.

This won't break any current code that depends on it.

I'll submit a PR if get it working.
