### ISSUE TITLE
Requesting license change.

### ISSUE THREAD

**Issue by jvdillon** [sofiat-olaosebikan/hopcroftkarp#6]
Hello admins. Thank you for adding such a useful piece of software!

I am the co-founder of "TensorFlow Probability" and was wondering if you'd be open to changing the license to something not copy-left, specifically "MIT License" or "Apache 2 License"?

If you could change to one of these, it would allow me to build on top of your work.

Thanks again!

Cheers,

Josh

**Comment by Upabjojr** [comment]
New PR in MatchPy to get rid of this GPL'd dependency by reimplementing the algorithm: https://github.com/HPAC/matchpy/pull/64

@jvdillon that code could be moved to a new package if I need a MIT-licensed package in `tensorflow_probability`.

**Comment by jvdillon** [comment]
Thanks!
